// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6zCFSN3kjbt-aK3O0DO77SO7SqXUX7kU',
    appId: '1:491080479663:web:21c4cefe438d3a59c9b55a',
    messagingSenderId: '491080479663',
    projectId: 'collectio-app-8479f',
    authDomain: 'collectio-app-8479f.firebaseapp.com',
    storageBucket: 'collectio-app-8479f.appspot.com',
    measurementId: 'G-V2XD2GM8RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxmNPNBvKKGREjsRTXJbSiK1pRQ3YHcGA',
    appId: '1:491080479663:android:913478ac51772193c9b55a',
    messagingSenderId: '491080479663',
    projectId: 'collectio-app-8479f',
    storageBucket: 'collectio-app-8479f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8Nd1__L_lkMGIWHHCes40jRbWACRYfw',
    appId: '1:491080479663:ios:9dcf3cc1b50e70fdc9b55a',
    messagingSenderId: '491080479663',
    projectId: 'collectio-app-8479f',
    storageBucket: 'collectio-app-8479f.appspot.com',
    iosClientId: '491080479663-i5kmps6npri4qiv7s1asdfi525mh8hb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8Nd1__L_lkMGIWHHCes40jRbWACRYfw',
    appId: '1:491080479663:ios:9dcf3cc1b50e70fdc9b55a',
    messagingSenderId: '491080479663',
    projectId: 'collectio-app-8479f',
    storageBucket: 'collectio-app-8479f.appspot.com',
    iosClientId: '491080479663-i5kmps6npri4qiv7s1asdfi525mh8hb0.apps.googleusercontent.com',
    iosBundleId: 'com.example.collectioapp',
  );
}
